version: "3.8"

services:
  db:
    container_name: finki-migrations
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - ./migration:/var/lib/postgresql/data
