version: "3.8"

services:
  db:
    container_name: finki-db
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data

  bot:
    container_name: finki-bot
    image: finki-discord-bot:latest
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./config:/app/config
      - ./sessions:/app/sessions
      - ./bot.log:/app/bot.log

  pgadmin:
    container_name: finki-pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    user: root
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
    volumes:
      - ./pgadmin:/var/lib/pgadmin
