version: "3.8"

services:
  db:
    container_name: finki-db
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data

  bot:
    container_name: finki-bot
    image: finki-discord-bot:latest
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./config:/app/config
      - ./sessions:/app/sessions
      - ./bot.log:/app/bot.log
