name: Bug Report
description: File a bug report
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or similar that will help us.
